service: onetable

plugins:
  - serverless-esbuild

package:
  patterns: 
    - './tables/**'
  individually: false

custom:
  stage: "${opt:stage, 'dev'}"
  esbuild:
    bundle: true
    minify: false
    treeShaking: true

provider:
  name: aws
  stage: "${self:custom.stage}"
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  versionFunctions: false
  logRetentionInDays: 7
  timeout: 45
  memorySize: 1024

  environment:
    PROFILE: ${self:custom.stage}
    LOG_FILTER: fatal, error, metrics, info, warn
    LOG_OVERRIDE: ""
    LOG_SAMPLE: ""

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:Query"
            - "dynamodb:Scan"
            - "dynamodb:GetItem"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:DescribeTable"
          Resource: "*"

functions:
  invoke:
    handler: Controller.handler
    timeout: 500

resources:
  Outputs:
    OnetableController:
      Export:
        Name: ControllerArn
      Value:
        "Fn::GetAtt": [ InvokeLambdaFunction, Arn ]